### ISSUE TITLE
 Allow Whitespace in Character/Account names again

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO-Other#3]
Its basically all in Tools.IsAllowedName function. BUT: This is a bit tricky with multiple whitespaces in names. there should be just 1 allowed.

**Comment by DX4D** [comment]
Multiple methods for accomplishing this are located in the _WIP_ folder as well as unit tests for most. Those methods need to all be tested for performance as this can be a very costly method. Do not trust the reported numbers, we need to retest all of the methods and find the best one so we don't have 2 seconds of lag added to character creation submission.

**Comment by DX4D** [comment]
(Close issue #11 in the other issue tracker once this is completed)

**Comment by DX4D** [comment]
@francy51 Please close this issue, I will open a new one.

**Comment by DX4D** [comment]
Finished
