### ISSUE TITLE
[ongoing] Improve build and testing workflow

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO-Other#33]
We should figure out a way to test zones in host and play or a faster way to test zoning mechanics. I sit here and change one line of code then spend 5 minutes doing a build and repeat that all day. Tasks that should take an hour are taking me all day because all I do is stare at build screens...

I would consider this high priority because it will save us loads of dev time, but at the same time it's probably not a quick solution either. We should probably suffer through it until next month unless there is a quick fix or we run out of things to do (:rofl: ). Next month though, we should think about escalating to a top priority

**Comment by francy51** [comment]
Attempting to improve through task #34

**Comment by wovencode** [comment]
step 1:

switching build mode is twice as fast now

**Comment by DX4D** [comment]
Quick Build Menu added...we can now build Client and Server with one click of the menu.

**Comment by DX4D** [comment]
Full Deployment option added to the Quick Build Menu...allows us to build one server and multiple clients for different platforms. (Full Deployment settings are inside of the script for now, could be improved by creating a config file in the future)

**Comment by DX4D** [comment]
@francy51 We can close this issue now, build workflow has been significantly improved
