### ISSUE TITLE
[task] Add features to editor

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO-Other#34]
OK thinking about the request to make things easier for testing etc.....

Since we can't do multi-zone testing on host/play...    could we extend the OpenMMO menu a tad  to do a build and run..   it would follow the manual steps we already do...

1)  Setup a server directory
2) Setup a Client Directory
3) Switch to server and build it
4) Switch to client and build it
5) Run server
6) Run Client

that way, although it may take some time it stops all the button clicking stuff..  you still have manual override if you want it, but you also have one button press if needed.

If everything also goes into the same place every time..(as it does for me now)  I also have a shortcut setup on my desktop to launch server and client that stays the same after each build anyway?
you could even have a 7) in there..  delete database option

**Comment by wovencode** [comment]
a build pipeline editor script would be perfect for that

**Comment by DX4D** [comment]
Finished pending testing - QuickBuildMenu has been added. It does everything but run the game for you :) Install paths are consistent, so a .bat file or similar (shortcut file) can be used to launch everything. Also has a Full Deployment option that can build a server plus multiple clients for different platforms.

**Comment by DX4D** [comment]
@francy51 Please close this issue
